[package]
edition = "2021"
name = "prominence"
version = "0.1.0"

[dependencies]
image = "0.24.2"
rand = "0.8.5"

serde = {version = "1.0.137", features = ["derive"], optional = true}

[features]
serde = ["dep:serde"]
