comment_width = 100
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
#max_width = 120
merge_derives = true
normalize_comments = true
reorder_imports = true
unstable_features = true
wrap_comments = true
